# Generated by Django 4.2.3 on 2023-07-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('appointmentid', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentdate', models.DateField()),
                ('appointmenttime', models.TimeField()),
                ('patientissue', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('doctorid', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=100)),
                ('daysavailable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=500)),
                ('response', models.IntegerField()),
                ('feedbacktype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('invoiceid', models.AutoField(primary_key=True, serialize=False)),
                ('invoicedate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentstatus', models.CharField(max_length=20)),
                ('paymentmethod', models.CharField(max_length=50)),
                ('appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('patientid', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bpm', models.IntegerField()),
                ('spo2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('prescriptionid', models.AutoField(primary_key=True, serialize=False)),
                ('prescriptiondate', models.DateField()),
                ('prescriptiondetail', models.CharField(max_length=500)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
                ('invoiceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='questionnairefacility',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('questioncontent', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentto', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='requestequipment',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('equipmentname', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='routinecheckup',
            fields=[
                ('checkupid', models.AutoField(primary_key=True, serialize=False)),
                ('checkupdate', models.DateField()),
                ('detail', models.CharField(max_length=500)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor')),
                ('patientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('contactno', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(choices=[('patient', 'patient'), ('staff', 'staff'), ('doctor', 'doctor'), ('admin', 'admin')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
        migrations.AddField(
            model_name='requestequipment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.user'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.user'),
        ),
        migrations.AddField(
            model_name='patient',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.user'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.user'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.user'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.user'),
        ),
        migrations.AddField(
            model_name='answer',
            name='questionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.questionnairefacility'),
        ),
        migrations.AddField(
            model_name='answer',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.user'),
        ),
    ]
